# Generated by Django 5.0.4 on 2024-05-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='lot_ID',
        ),
    ]
