# Generated by Django 5.0.4 on 2024-05-06 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_rawmaterial_rename_product_lot_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='machine_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotes.machine'),
        ),
    ]
