# Generated by Django 5.0.4 on 2024-05-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_distribution_flavor_lot_rawmaterial_productionline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='expiry_Date',
            field=models.DateTimeField(),
        ),
    ]
