# Generated by Django 5.0.4 on 2024-05-06 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_product_machine_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lot',
            name='delivery_Date',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='sell_Cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='distribution',
            name='sell_Cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lot',
            name='qualityStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotes.flavor'),
        ),
    ]
