# Generated by Django 4.2.13 on 2024-05-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_flavor_productionline_delete_machine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionline',
            old_name='progresField',
            new_name='progresFielda',
        ),
    ]
