# Generated by Django 4.2.13 on 2024-05-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_rename_progresfield_productionline_progresfielda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionline',
            old_name='progresFielda',
            new_name='progresField',
        ),
    ]
