# Generated by Django 5.0.4 on 2024-05-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_flavor_remove_lot_delivery_date_remove_lot_sell_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flavor',
            new_name='flavor_id',
        ),
    ]
