# Generated by Django 5.0.4 on 2024-05-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0005_rename_flavor_product_flavor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QualityReport',
        ),
    ]
